#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                    ZNode Setup Script                          ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# --- Check Node.js version ---
echo "[1/5] Checking Node.js version..."
if ! command -v node >/dev/null 2>&1; then
  echo "❌ ERROR: Node.js is not installed."
  echo "   Please install Node.js >= 18 from https://nodejs.org/"
  exit 1
fi

NODE_VER_RAW="$(node -v | sed 's/^v//')"
NODE_MAJOR="${NODE_VER_RAW%%.*}"
if [ "${NODE_MAJOR:-0}" -lt 18 ]; then
  echo "❌ ERROR: Node.js >= 18 required, found v$NODE_VER_RAW"
  echo "   Please upgrade Node.js from https://nodejs.org/"
  exit 1
fi

echo "✓ Node.js v$NODE_VER_RAW detected"
echo ""

# --- Install dependencies ---
echo "[2/5] Installing npm dependencies..."
if [ -f package-lock.json ]; then
  npm ci --omit=dev --quiet
else
  npm install --omit=dev --quiet
fi
echo "✓ Dependencies installed"
echo ""

# --- Collect configuration ---
echo "[3/5] Configuring environment..."
ENV_FILE="$SCRIPT_DIR/.env"
if [ -f "$ENV_FILE" ]; then
  echo "⚠️  Existing .env file detected"
  read -r -p "Overwrite existing .env? [y/N]: " ans
  case "${ans,,}" in
    y|yes) echo "Overwriting existing configuration..." ;;
    *) echo "✓ Keeping existing .env"; echo ""; echo "Setup complete! Use ./start to launch the node."; exit 0;;
  esac
fi

# Defaults
DEFAULT_RPC_URL="https://ethereum-sepolia-rpc.publicnode.com"
DEFAULT_MONERO_WALLET_PASSWORD="znode_monero_pw"
DEFAULT_MONERO_WALLET_RPC_USER="znode_rpc"
DEFAULT_MONERO_WALLET_RPC_PASSWORD="znode_rpc_pw"
DEFAULT_P2P_BOOTSTRAP_PEERS=/ip4/185.191.116.142/tcp/26005/p2p/12D3KooWMSmo8WiqPgGp4PJXNAEx95n9KFQC25WeFW9A7mvmS2qR

echo ""
echo "Required Configuration:"
echo "----------------------"

# Ethereum RPC URL
read -r -p "Ethereum Sepolia RPC URL [press Enter for default]: " RPC_URL
RPC_URL="${RPC_URL:-$DEFAULT_RPC_URL}"

# Ethereum Private Key
read -r -s -p "Ethereum private key (0x...): " PRIVATE_KEY
echo ""
while [ -z "${PRIVATE_KEY}" ]; do
  echo "⚠️  Private key is required."
  read -r -s -p "Ethereum private key (0x...): " PRIVATE_KEY
  echo ""
done

if [[ ! "$PRIVATE_KEY" =~ ^0x ]]; then
  PRIVATE_KEY="0x${PRIVATE_KEY}"
fi

# Monero Fee Address
read -r -p "Monero fee address for receiving exchange fees: " MONERO_FEE_ADDRESS
while [ -z "${MONERO_FEE_ADDRESS}" ]; do
  echo "⚠️  Monero fee address is required."
  read -r -p "Monero fee address: " MONERO_FEE_ADDRESS
done

MONERO_WALLET_PASSWORD="${DEFAULT_MONERO_WALLET_PASSWORD}"
echo "ℹ️  Generated Monero wallet password (stored in .env only)"

# All other settings use defaults
MONERO_RPC_URL="http://127.0.0.1:18083"
MONERO_WALLET_RPC_USER="${DEFAULT_MONERO_WALLET_RPC_USER}"
MONERO_WALLET_RPC_PASSWORD="${DEFAULT_MONERO_WALLET_RPC_PASSWORD}"

# Public IP used for P2P announcements (optional but recommended)
echo ""
read -r -p "Public IP address for P2P (optional, press Enter to skip): " PUBLIC_IP

P2P_BOOTSTRAP_PEERS=/ip4/185.191.116.142/tcp/26005/p2p/12D3KooWMSmo8WiqPgGp4PJXNAEx95n9KFQC25WeFW9A7mvmS2qR

echo ""
echo "[4/5] Writing configuration..."

cat > "$ENV_FILE" << EOF_ENV
# Auto-generated by setup.sh on $(date)

PRIVATE_KEY=${PRIVATE_KEY}
RPC_URL=${RPC_URL}
MONERO_WALLET_PASSWORD=${MONERO_WALLET_PASSWORD}

TEST_MODE=0
DRY_RUN=0

P2P_IMPL=libp2p
P2P_REQUIRE_E2E=1
P2P_PORT=26005
ORACLE_P2P_PORT=26015
PUBLIC_IP=${PUBLIC_IP}
P2P_BOOTSTRAP_PEERS=/ip4/185.191.116.142/tcp/26005/p2p/12D3KooWMSmo8WiqPgGp4PJXNAEx95n9KFQC25WeFW9A7mvmS2qR

MONERO_RPC_URL=${MONERO_RPC_URL}
MONERO_WALLET_RPC_USER=${MONERO_WALLET_RPC_USER}
MONERO_WALLET_RPC_PASSWORD=${MONERO_WALLET_RPC_PASSWORD}

# Staking configuration
MONERO_FEE_ADDRESS=${MONERO_FEE_ADDRESS}

REGISTRY_ADDR=0x82a9E750417EfdC22ff32d7cfF25C283d6C0cd87
STAKING_ADDR=0x14b00D03EcB5C3cca59e6feCf2Df593aBc6346cd
ZFI_ADDR=0x84e560eF51A9a2DBE51BFBB935bDf658B95d6d81
COORDINATOR_ADDR=0x6119195691d1C3D5C4D4C91f61015080F879a84c

HEARTBEAT_INTERVAL=900
STALE_ROUND_MIN_AGE_MS=600000
STICKY_QUEUE=0
FORCE_SELECT=0
EOF_ENV

chmod 600 "$ENV_FILE" || true
echo "✓ Configuration written to $ENV_FILE"
echo ""

echo "[5/5] Validating configuration..."
if node --check node.js 2>/dev/null; then
  echo "✓ Syntax validation passed"
else
  echo "⚠️  Warning: Could not validate syntax"
fi
echo ""

# Ensure ufw is installed so we can manage firewall rules automatically
if ! command -v ufw >/dev/null 2>&1; then
  if command -v apt-get >/dev/null 2>&1; then
    echo "[Firewall] ufw not found; installing via apt-get..."
    apt-get update -y >/dev/null 2>&1 && apt-get install -y ufw >/dev/null 2>&1       || echo "[Firewall] Warning: failed to install ufw. Please install it manually and open ports 26005 and 26015."
  else
    echo "[Firewall] ufw not found and apt-get not available. Please install ufw manually and open ports 26005 and 26015."
  fi
fi

# Optional firewall configuration for P2P ports
# Attempts to open inbound TCP ports used by the node and heartbeat oracle.
if command -v ufw >/dev/null 2>&1; then
  echo "[Firewall] Detected ufw; ensuring P2P ports 26005 and 26015 are open..."
  ufw allow 26005/tcp >/dev/null 2>&1 || echo "[Firewall] Warning: failed to run 'ufw allow 26005/tcp'"
  ufw allow 26015/tcp >/dev/null 2>&1 || echo "[Firewall] Warning: failed to run 'ufw allow 26015/tcp'"
else
  echo "[Firewall] ufw not found. Please ensure TCP ports 26005 and 26015 are open inbound for P2P."
fi

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                    Setup Complete!                             ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Next steps:"
echo "  1. Start the node: ./start"
echo "  2. View logs: tail -f znode.log"
echo ""
echo "⚠️  IMPORTANT:"
echo "  - Node configured for production (Sepolia testnet)"
echo "  - See README.md for full documentation"
echo ""
